---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  results:
    - name: output
  params:
    - name: CONTEXT
      type: string
      default: "."
    - name: ARGS
      type: string
    - name: NODE_IMAGE
      type: string
      default: "registry.access.redhat.com/ubi8/nodejs-16" 
  steps:
    - image: $(params.NODE_IMAGE)
      name: npm-run
      script: |
        npm $(params.ARGS) | tee $(results.output.path)
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      env:
        - name: CI
          value: "true"	
