---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-build
spec:
  workspaces:
    - name: shared
  params:
    - name: IMAGE_NAME
      type: string
      default: "exchange"
    - name: GIT_REPO
      type: string
      default: "https://github.com/Yujin-Zhu/DO288-apps" 
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: APP_PATH
      type: string
      default: "apps/pipelines-creation/exchange"

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: sslVerify
          value: false
      workspaces: 
        - name: output
          workspace: shared
    - name: build-app
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: docker.io/yujinzhu/$(params.IMAGE_NAME):latest
        - name: DOCKERFILE
          value: Containerfile
        - name: CONTEXT
          value: $(params.APP_PATH)
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared
        
          

