apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "20"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"expense:4.14"},"fieldPath":"spec.template.spec.containers[?(@.name==\"expense\")].image"}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"image.openshift.io/triggers":"[{\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"expense:4.14\"},\"fieldPath\":\"spec.template.spec.containers[?(@.name==\\\"expense\\\")].image\"}]","openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"expense","app.kubernetes.io/component":"expense","app.kubernetes.io/instance":"expense"},"name":"expense","namespace":"yujin-zhu-dev"},"spec":{"replicas":3,"selector":{"matchLabels":{"deployment":"expense"}},"strategy":{},"template":{"metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"deployment":"expense"}},"spec":{"containers":[{"image":"docker.io/yujinzhu/ocpdev-expense-service:4.14","name":"expense","ports":[{"containerPort":8080,"protocol":"TCP"},{"containerPort":8443,"protocol":"TCP"}],"resources":{"limits":{"cpu":"0.1","memory":"200Mi"},"requests":{"cpu":"0.1","memory":"200Mi"}}}]}}},"status":{}}
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-11-25T10:02:08Z"
  generation: 29
  labels:
    app: expense
    app.kubernetes.io/component: expense
    app.kubernetes.io/instance: expense
  name: expense
  namespace: yujin-zhu-dev
  resourceVersion: "3156215405"
  uid: bb046e78-e31d-4b8b-ade4-a2dad5a1edca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: expense
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-11-25T12:27:51+01:00"
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: expense
    spec:
      containers:
      - env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: DATABASE_NAME
              name: postgresql
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: postgresql
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: postgresql
        image: docker.io/yujinzhu/ocpdev-expense-service@sha256:c775a966dd83c961c69a1ac3e1306abf2bbc06af5c8f3a771b51cdeae3693fbd
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: expense
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-11-25T11:31:29Z"
    lastUpdateTime: "2024-11-25T11:31:29Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-11-25T12:10:35Z"
    lastUpdateTime: "2024-11-25T12:10:35Z"
    message: ReplicaSet "expense-6bf54f7b5b" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 29
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
