apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"expense","app.kubernetes.io/component":"expense","app.kubernetes.io/instance":"expense"},"name":"expense","namespace":"yujin-zhu-dev"},"spec":{"ports":[{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080},{"name":"8443-tcp","port":8443,"protocol":"TCP","targetPort":8443}],"selector":{"deployment":"expense"}},"status":{"loadBalancer":{}}}
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2024-11-25T10:02:08Z"
  labels:
    app: expense
    app.kubernetes.io/component: expense
    app.kubernetes.io/instance: expense
  name: expense
  namespace: yujin-zhu-dev
  resourceVersion: "3155884979"
  uid: 7b24d6ed-cea3-428c-9370-ada94cea5f75
spec:
  clusterIP: 172.30.37.151
  clusterIPs:
  - 172.30.37.151
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: expense
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
