apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: famous-quotes
spec:
  host: famous-quotes-yujin-zhu-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
  port:
    targetPort: https
  to:
    kind: Service
    name: famous-quotes
