---
# Source: todo-list/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-list-mariadb
  namespace: "yujin-zhu-dev"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/managed-by: Helm
  annotations:
automountServiceAccountToken: false
---
# Source: todo-list/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: todo-list-mariadb
  namespace: "yujin-zhu-dev"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "SEZ1SzA4NGtkQg=="
  mariadb-password: "dG9kb3B3ZA=="
---
# Source: todo-list/charts/mariadb/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-list-mariadb
  namespace: "yujin-zhu-dev"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    long_query_time=10.0
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
# Source: todo-list/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-list-mariadb
  namespace: "yujin-zhu-dev"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: 
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/component: primary
---
# Source: todo-list/templates/archive/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-list-mariadb
  labels:
    helm.sh/chart: todo-list-0.1.0
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/instance: todo-list
---
# Source: todo-list/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-mariadb
  labels:
    helm.sh/chart: todo-list-0.1.0
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-list
      app.kubernetes.io/instance: todo-list
  template:
    metadata:
      labels:
        helm.sh/chart: todo-list-0.1.0
        app.kubernetes.io/name: todo-list
        app.kubernetes.io/instance: todo-list
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: todo-list
          securityContext:
            {}
          image: "docker.io/yujinzhu/todobackend:release-46"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {}
          env:
            - name: DATABASE_USER
              value: todouser
            - name: DATABASE_PASSWORD
              value: todopwd
            - name: DATABASE_NAME
              value: tododb
            - name: DATABASE_SVC
              value: mariadb
---
# Source: todo-list/charts/mariadb/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-list-mariadb
  namespace: "yujin-zhu-dev"
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.3.3
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: 
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: todo-list
      app.kubernetes.io/component: primary
  serviceName: todo-list-mariadb
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: a298b5274a178ca0d3d47e28c3b38fe3bc77e25a4b73487e7bf4c7713c5df4d2
      labels:
        app.kubernetes.io/name: mariadb
        helm.sh/chart: mariadb-11.3.3
        app.kubernetes.io/instance: todo-list
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: primary
    spec:
      
      serviceAccountName: todo-list-mariadb
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mariadb
                    app.kubernetes.io/instance: todo-list
                    app.kubernetes.io/component: primary
                namespaces:
                  - "yujin-zhu-dev"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      containers:
        - name: mariadb
          image: docker.io/yujinzhu/bitnami/mariadb:10.5.10-debian-10-r0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-list-mariadb
                  key: mariadb-root-password
            - name: MARIADB_USER
              value: "todouser"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-list-mariadb
                  key: mariadb-password
            - name: MARIADB_DATABASE
              value: "tododb"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mysqladmin status -uroot -p"${password_aux}"
          resources: 
            limits: {}
            requests: {}
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
            - name: config
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
      volumes:
        - name: config
          configMap:
            name: todo-list-mariadb
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: 
          app.kubernetes.io/name: mariadb
          app.kubernetes.io/instance: todo-list
          app.kubernetes.io/component: primary
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
# Source: todo-list/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "todo-list-mariadb-test-connection"
  labels:
    helm.sh/chart: todo-list-0.1.0
    app.kubernetes.io/name: todo-list
    app.kubernetes.io/instance: todo-list
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['todo-list-mariadb:3000']
  restartPolicy: Never
