FROM registry.access.redhat.com/ubi8/openjdk-17:1.20-2.1731461738
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src src
RUN mvn clean package

CMD ["java", "-jar", "target/expense-service-1.0.0-SNAPSHOT-runner.jar"]
